"""add_credit_card_fields_to_accounts

Revision ID: ec50fbee7599
Revises: 30fc9b4bcfa6
Create Date: 2026-02-08 12:22:16.232304+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec50fbee7599'
down_revision: Union[str, None] = '30fc9b4bcfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('credit_limit', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('interest_rate', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('billing_day', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('grace_period_days', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('minimum_payment_percent', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('last_statement_date', sa.Date(), nullable=True))
    op.add_column('accounts', sa.Column('payment_due_date', sa.Date(), nullable=True))
    op.add_column('accounts', sa.Column('card_last_digits', sa.String(length=4), nullable=True))
    op.add_column('accounts', sa.Column('card_keywords', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'card_keywords')
    op.drop_column('accounts', 'card_last_digits')
    op.drop_column('accounts', 'payment_due_date')
    op.drop_column('accounts', 'last_statement_date')
    op.drop_column('accounts', 'minimum_payment_percent')
    op.drop_column('accounts', 'grace_period_days')
    op.drop_column('accounts', 'billing_day')
    op.drop_column('accounts', 'interest_rate')
    op.drop_column('accounts', 'credit_limit')
    # ### end Alembic commands ###
