"""add description to accounts

Revision ID: b3a4a541f17c
Revises: ec50fbee7599
Create Date: 2026-02-20 14:07:29.851737+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a4a541f17c'
down_revision: Union[str, None] = 'ec50fbee7599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'description')
    # ### end Alembic commands ###
